# pog pog pogu

name: Deploy

# on:
#     release:
#       types:
#         - "released"
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: executing remote build process
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: ls websites/uoaDiscordsFrontend.sh
